### ISSUE TITLE
Develop and Test support analytic endpoints

### ISSUE THREAD

**Issue by SupremeTechnopriest** [luceracloud/node-helpscout#2]
this may require getting on IRC with the helpscout guys.  Not sure how far along they are.  They said all they had to do was document the rest endpoints about 2 months ago...

**Comment by dang0ld** [comment]
Apparently this is "on the horizon" - but with no specific ETA they can comment upon.

**Comment by SupremeTechnopriest** [comment]
Could we possibly go to their portal and reverse engineer the http calls?  Last i spoke with them the endpoints are available, just not documented.

**Comment by dang0ld** [comment]
I'll see what I can do
